config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
   devise_for :users, controllers: { sessions: "app_sessions" }
   # mount Tiun::Engine, at: '/api'
   # Tiun::Engine.routes
   root to: "application#home"

   resources :users, only: %i(index show)
   get "/me" => "users#me"
   put "/me" => "users#upme"
   resources :novelties, path: "/news", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :libra, path: "/library", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :meanings, path: "/m", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :languages, path: "/l", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :alphabeths, path: "/a", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :dictionaries, path: "/d", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :grammars, path: "/g", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :attitudes, path: "/at", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :tags, path: "/t", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :pieces, path: "/p", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :articles, path: "/c", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :dicta, path: "/s", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :socials, path: "/so", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :accounts, path: "/ac", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)

   mount(Sidekiq::Web => "/dashboard/sidekiq") if !Rails.env.test?

   get "/404" => "errors#not_found"
   get "/500" => "errors#exception"
end

app/controllers/libra_controller.rb
# frozen_string_literal: true

class LibraController < ApplicationController
   skip_before_action :authenticate_user!, only: [:index, :show]

   before_action :set_librum, only: %i(show update destroy)
   before_action :init_librum, only: :create
   before_action :authorize_librum, only: %i(create update destroy)

   has_scope :by_tags, only: %i(index), type: :array

   # GET /libra
   def index
      respond_to do |format|
         format.json do
            render plain: {
               list: @objects.jsonize(context),
               page: @page,
               per: @per,
               total: @objects.total_count
            }.to_json
         end
      end
   end

   # GET /libra/1
   def show
      respond_to do |format|
         format.json { render json: @librum.jsonize(context) }
      end
   end

   # POST /libra
   def create
      @librum.save!

      respond_to do |format|
         format.json { head :ok }
      end
   end

   # PATCH/PUT /libra/1
   def update
      @librum.update!(librum_params)

      respond_to do |format|
         format.json { head :ok }
      end
   end

   # DELETE /libra/1
   def destroy
      @librum.destroy

      respond_to do |format|
         format.json { head :ok }
      end
   end

   private
      # Use callbacks to share common setup or constraints between actions.
      def set_librum
         @librum = Librum.find(params[:id])
      end

      def init_librum
         @librum = model.new(librum_params)
      end

      def authorize_librum
         authorize @librum
      end

      def model
         Librum
      end

      # Only allow a list of trusted parameters through.
      def librum_params
         params.require(:librum).permit(:text, :title, :author_id, :abstract, :cover_uri, tags: [])
      end

      def context
         @context ||= { except: %i(created_at updated_at tsv) }
      end
end

app/views/libra/_form.html.erb
<%= form_with(model: librum) do |form| %>
  <% if librum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(librum.errors.count, "error") %> prohibited this librum from being saved:</h2>

      <ul>
        <% librum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/libra/edit.html.erb
<h1>Editing Librum</h1>

<%= render 'form', librum: @librum %>

<%= link_to 'Show', @librum %> |
<%= link_to 'Back', libra_path %>

app/views/libra/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Libra</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libra.each do |librum| %>
      <tr>
        <td><%= librum.text %></td>
        <td><%= librum.title %></td>
        <td><%= link_to 'Show', librum %></td>
        <td><%= link_to 'Edit', edit_librum_path(librum) %></td>
        <td><%= link_to 'Destroy', librum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Librum', new_librum_path %>

app/views/libra/new.html.erb
<h1>New Librum</h1>

<%= render 'form', librum: @librum %>

<%= link_to 'Back', libra_path %>

app/views/libra/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @librum.text %>
</p>

<p>
  <strong>Title:</strong>
  <%= @librum.title %>
</p>

<%= link_to 'Edit', edit_librum_path(@librum) %> |
<%= link_to 'Back', libra_path %>