config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
   devise_for :users, controllers: { sessions: "app_sessions" }
   # mount Tiun::Engine, at: '/api'
   # Tiun::Engine.routes
   root to: "application#home"

   resources :users, only: %i(index show)
   get "/me" => "users#me"
   put "/me" => "users#upme"
   resources :novelties, path: "/news", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :libra, path: "/library", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :meanings, path: "/m", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :languages, path: "/l", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :alphabeths, path: "/a", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :dictionaries, path: "/d", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :grammars, path: "/g", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :attitudes, path: "/at", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :tags, path: "/t", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :pieces, path: "/p", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :articles, path: "/c", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :dicta, path: "/s", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :socials, path: "/so", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)
   resources :accounts, path: "/ac", defaults: { format: :json }, constraints: { format: "json" }, except: %i(new edit)

   mount(Sidekiq::Web => "/dashboard/sidekiq") if !Rails.env.test?

   get "/404" => "errors#not_found"
   get "/500" => "errors#exception"
end

app/models/novelty.rb
# frozen_string_literal: true

class Novelty < Librum
   default_scope { unscope(:where).where(type: "Novelty") }
end

app/controllers/novelties_controller.rb
# frozen_string_literal: true

class NoveltiesController < ApplicationController
   skip_before_action :authenticate_user!, only: [:index, :show]

   before_action :set_novelty, only: %i(show update destroy)
   before_action :init_novelty, only: :create
   before_action :authorize_novelty, only: %i(create update destroy)

   has_scope :by_tags, only: %i(index), type: :array

   # GET /novelties
   def index
      respond_to do |format|
         format.json do
            render plain: {
               list: @objects.jsonize(context),
               page: @page,
               per: @per,
               total: @objects.total_count
            }.to_json
         end
      end
   end

   # GET /novelties/1
   def show
      respond_to do |format|
         format.json { render json: @novelty.jsonize(context) }
      end
   end

   # POST /novelties
   def create
      @novelty.save!

      respond_to do |format|
         format.json { head :ok }
      end
   end

   # PATCH/PUT /novelties/1
   def update
      @novelty.update!(novelty_params)

      respond_to do |format|
         format.json { head :ok }
      end
   end

   # DELETE /novelties/1
   def destroy
      @novelty.destroy

      respond_to do |format|
         format.json { head :ok }
      end
   end

   private
      # Use callbacks to share common setup or constraints between actions.
      def set_novelty
         @novelty = model.find(params[:id])
      end

      def init_novelty
         @novelty = model.new(novelty_params)
      end

      def authorize_novelty
         authorize @novelty
      end

      def model
         Novelty
      end

      # Only allow a list of trusted parameters through.
      def novelty_params
         params.require(:novelty).permit(:text, :title, :author_id, :abstract, :cover_uri, tags: [])
      end

      def context
         @context ||= { except: %i(created_at updated_at tsv) }
      end
end

app/views/novelties/_form.html.erb
<%= form_with(model: novelty) do |form| %>
  <% if novelty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(novelty.errors.count, "error") %> prohibited this novelty from being saved:</h2>

      <ul>
        <% novelty.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/novelties/edit.html.erb
<h1>Editing Novelty</h1>

<%= render 'form', novelty: @novelty %>

<%= link_to 'Show', @novelty %> |
<%= link_to 'Back', novelties_path %>

app/views/novelties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Novelties</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @novelties.each do |novelty| %>
      <tr>
        <td><%= novelty.text %></td>
        <td><%= novelty.title %></td>
        <td><%= link_to 'Show', novelty %></td>
        <td><%= link_to 'Edit', edit_novelty_path(novelty) %></td>
        <td><%= link_to 'Destroy', novelty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Novelty', new_novelty_path %>

app/views/novelties/new.html.erb
<h1>New Novelty</h1>

<%= render 'form', novelty: @novelty %>

<%= link_to 'Back', novelties_path %>

app/views/novelties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @novelty.text %>
</p>

<p>
  <strong>Title:</strong>
  <%= @novelty.title %>
</p>

<%= link_to 'Edit', edit_novelty_path(@novelty) %> |
<%= link_to 'Back', novelties_path %>